In [0]:
import numpy as np

# 1.
평균 0.1, 표준편차 2인 정규분포에서 16개 샘플링 한 것을 M에 저장.

In [0]:
np.random.seed(seed=10)

In [0]:
''' 
output:
array([ 2.76317301,  1.53055795, -2.99080058,  0.0832323 ,  1.34267195,
       -1.34017112,  0.63102317,  0.31709705,  0.10858286, -0.24920042,
        0.96605238,  2.50607475, -1.83013134,  2.15654816,  0.55726026,
        0.99027523])
'''
M = 2*np.random.randn(16)+0.1
M

array([ 2.76317301,  1.53055795, -2.99080058,  0.0832323 ,  1.34267195,
       -1.34017112,  0.63102317,  0.31709705,  0.10858286, -0.24920042,
        0.96605238,  2.50607475, -1.83013134,  2.15654816,  0.55726026,
        0.99027523])

# 2.
위에서 작성한 배열 M을 4*4의 매트릭스 형태로 만들것.  
즉, shape을 바꿔준다.

In [0]:
'''
output:
array([[ 2.76317301,  1.53055795, -2.99080058,  0.0832323 ],
       [ 1.34267195, -1.34017112,  0.63102317,  0.31709705],
       [ 0.10858286, -0.24920042,  0.96605238,  2.50607475],
       [-1.83013134,  2.15654816,  0.55726026,  0.99027523]])
'''
M = M.reshape(4, 4)
M

array([[ 2.76317301,  1.53055795, -2.99080058,  0.0832323 ],
       [ 1.34267195, -1.34017112,  0.63102317,  0.31709705],
       [ 0.10858286, -0.24920042,  0.96605238,  2.50607475],
       [-1.83013134,  2.15654816,  0.55726026,  0.99027523]])

# 3
벡터 x를 위에서 작성한 M과 곱해준 결과 값을 y에 저장할 것.

In [0]:
x = np.array([7, -2, 5, -1])

In [0]:
# output: array([  1.24385994,  14.91706468,   3.58266803, -15.32798962])
y = np.dot(M, x)
y

array([  1.24385994,  14.91706468,   3.58266803, -15.32798962])

# 4
매트릭스 M의 determinant를 이용하여 inverse가 존재 여부 판별. 존재하면 True, 아니면 False

In [0]:
# output: True
np.linalg.det(M)!=0

True

# 5
매트릭스 M의 inverse matrix를 구해서 M_inv에 저장.

In [0]:
'''
output:
array([[ 0.18928642,  0.97415101, -0.30189282,  0.43615229],
       [ 0.16306094,  0.71171647, -0.38993855,  0.745207  ],
       [-0.07500374,  1.25160174, -0.46311119,  0.77751595],
       [ 0.03692593, -0.45390861,  0.55185792, -0.24451541]])
'''
M_inv = np.linalg.inv(M)
M_inv

array([[ 0.18928642,  0.97415101, -0.30189282,  0.43615229],
       [ 0.16306094,  0.71171647, -0.38993855,  0.745207  ],
       [-0.07500374,  1.25160174, -0.46311119,  0.77751595],
       [ 0.03692593, -0.45390861,  0.55185792, -0.24451541]])

# 6
M_inv와 y를 곱해준 결과와 x와 비교해볼 것.

In [0]:
x

array([ 7, -2,  5, -1])

In [0]:
# output: array([ 7., -2.,  5., -1.])
np.dot(M_inv, y)

array([ 7., -2.,  5., -1.])