In [0]:
import numpy as np

# 1
배열의 최대값, 최소값을 구하기

In [0]:
arr = np.array([ 46, -71,   9, 218, 151, 102, 240, -65,  70, 219, -26, 284,  74,
       257, -91, 126, 116, 294, 294,  78,  18, 165, 261,  93, -45, -67,
       -10, 276, -22, -41, 239,  89, 227, 259, 191,  11,  20,   7,  -6])

In [0]:
'''
output:
Maximum Value:  294
Minimum Value:  -91
'''

Maximum Value:  294
Minimum Value:  -91


# 2
배열의 최대값, 최소값을 갖는 배열의 인덱스를 각각 구하기

In [0]:
arr = np.array([ 46, -71,   9, 218, 151, 102, 240, -65,  70, 219, -26, 284,  74,
       257, -91, 126, 116, 294, 294,  78,  18, 165, 261,  93, -45, -67,
       -10, 276, -22, -41, 239,  89, 227, 259, 191,  11,  20,   7,  -6])

In [0]:
'''
output:
index of maximum Value:  17
index of minimum Value:  14
'''

index of maximum Value:  17
index of minimum Value:  14


# 3
배열의 unique한 값을 추출. 

In [0]:
arr = np.array([10, 110, 20, 40, 10, 620,  60, 110, 30, 100, 620, 170, 870, 390, 620, 30, 30, 110, 20, 30, 40, 60, 870, 100])

In [0]:
# output:array([ 10,  20,  30,  40,  60, 100, 110, 170, 390, 620, 870])

array([ 10,  20,  30,  40,  60, 100, 110, 170, 390, 620, 870])

# 4
두 배열의 공통 원소를 추출.

In [0]:
arr1 = np.array([0, 10, 20, 40, 60, 30, 100, 620, 170, 870, 390, 110, 130, 160, 330])
arr2 =  np.array([120, 910, 390, 130, 20, 30, 40, 0, 120])

In [0]:
# output: array([  0,  20,  30,  40, 130, 390])

array([  0,  20,  30,  40, 130, 390])

# 5
두 배열의 차를 구하기.

In [0]:
arr1 = np.array([6985, 7978, 1700, 3278, 4893, 4798, 3593, 2265, 3308])
arr2 = np.array([3724, 3737, 4867, 4218, 7542, 4351, 2259, 4568, 6230])

In [0]:
# output: array([ 3261,  4241, -3167,  -940, -2649,   447,  1334, -2303, -2922])

array([ 3261,  4241, -3167,  -940, -2649,   447,  1334, -2303, -2922])

# 6
다음 매트릭스의 2번째 행(index=1)에만 100을 더하기.

In [0]:
arr = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
'''
output:
array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [110, 111, 112, 113, 114],
       [ 15,  16,  17,  18,  19]])
'''

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [110, 111, 112, 113, 114],
       [ 15,  16,  17,  18,  19]])

# 7
다음 매트릭스의 2번째 열(index=1)에만 100을 곱하기.

In [0]:
arr = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
'''
output:
array([[   0,    1,  200,    3,    4],
       [   5,    6,  700,    8,    9],
       [  10,   11, 1200,   13,   14],
       [  15,   16, 1700,   18,   19]])
'''

array([[   0,    1,  200,    3,    4],
       [   5,    6,  700,    8,    9],
       [  10,   11, 1200,   13,   14],
       [  15,   16, 1700,   18,   19]])

# 8
두 배열의 같은 위치에 있는 원소 중 큰 값을 반환

In [0]:
arr1 = np.array([-100, -90, -80, -70, -60, -50, -40, -30, 20, -10, 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
arr2 = np.array([-80, 80, -80, 80, -80, 80, -80, 80, -80, 80, -80, 80, -80, 80, -80, 80, -80, 80, -80, 80])

In [0]:
# output: array([-80,  80, -80,  80, -60,  80, -40,  80,  20,  80,   0,  80,  20,  80,  40,  80,  60,  80,  80,  90])

array([-80,  80, -80,  80, -60,  80, -40,  80,  20,  80,   0,  80,  20,
        80,  40,  80,  60,  80,  80,  90])

# 9
다음 배열의 평균과 표준편차를 반환

In [0]:
arr = np.array([48.41893797, 32.05097847, 41.37111227, 39.93527883, 46.38001546,
       11.40556903, 30.10631704, 26.44617729, 18.79948929, 24.93398529])

In [0]:
'''
output:
평균: 31.984786094000004
표준편차: 11.445071707360972
'''

평균: 31.984786094000004
표준편차: 11.445071707360972


# 10
두 배열의  correlation coefficient matrix를 구하기


In [0]:
arr1 = np.array([6.985, 7.978, 1.7  , 3.278, 4.893, 4.798, 3.593, 2.265, 3.308])
arr2 = np.array([3.724, 3.737, 4.867, 4.218, 7.542, 4.351, 2.259, 4.568, 6.23 ])

In [0]:
'''
output:
array([[ 1.        , -0.16158527],
       [-0.16158527,  1.        ]])
'''


array([[ 1.        , -0.16158527],
       [-0.16158527,  1.        ]])

# 11
매트릭스 열을 기준으로 1번째 열은 100, 2번째 열은 200, 3번째 열은 300, 4번째 열은 400, 5번째 열은 500 더하기 

In [0]:
arr = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
'''
output:
array([[100, 201, 302, 403, 504],
       [105, 206, 307, 408, 509],
       [110, 211, 312, 413, 514],
       [115, 216, 317, 418, 519]])
'''

array([[100, 201, 302, 403, 504],
       [105, 206, 307, 408, 509],
       [110, 211, 312, 413, 514],
       [115, 216, 317, 418, 519]])

# 12
매트릭스 행을 기준으로 1번째 행은 100, 2번째 행은 200, 3번째 행은 300, 4번째 행은 400을 더하기 

In [0]:
arr = np.array([[ 0,  1,  2,  3,  4],
                [ 5,  6,  7,  8,  9],
                [10, 11, 12, 13, 14],
                [15, 16, 17, 18, 19]])

In [0]:
'''
output:
array([[100, 101, 102, 103, 104],
       [205, 206, 207, 208, 209],
       [310, 311, 312, 313, 314],
       [415, 416, 417, 418, 419]])
'''

array([[100, 101, 102, 103, 104],
       [205, 206, 207, 208, 209],
       [310, 311, 312, 313, 314],
       [415, 416, 417, 418, 419]])

# 13
1. 매트릭스의 누적 합을 계산하기(행으로 누적)
    - (i번째 행까지 누적+ (i+1)번째 행 = (i+1)번째 행까지 누적)
2. 매트릭스의 누적 합을 계산하기(열로 누적)  
     - (j번째 열까지 누적+ (j+1)번째 열 = (j+1)번째 열까지 누적)
3. 매트릭스의 누적 합을 계산하기(flattend 된 배열로 보고)

In [0]:
arr = np.array([[ 0,  1,  2,  3,  4],
                [ 5,  6,  7,  8,  9],
                [10, 11, 12, 13, 14],
                [15, 16, 17, 18, 19]])

In [0]:
'''
1.
[[ 0  1  2  3  4]
 [ 5  7  9 11 13]
 [15 18 21 24 27]
 [30 34 38 42 46]]
2.
[[ 0  1  3  6 10]
 [ 5 11 18 26 35]
 [10 21 33 46 60]
 [15 31 48 66 85]]
3.
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]
'''

1.
[[ 0  1  2  3  4]
 [ 5  7  9 11 13]
 [15 18 21 24 27]
 [30 34 38 42 46]]
2.
[[ 0  1  3  6 10]
 [ 5 11 18 26 35]
 [10 21 33 46 60]
 [15 31 48 66 85]]
3.
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]


# 14
원소가 -5보다 크면서 5보다 작거나 같으면 True, 이외에는 False 값을 가지는 불리언 배열로 반환
 
 bool array

In [0]:
arr = np.array([[ 16, -13,  18, -28,   6, -15,   7,  28],
                [ 19,  22,  25,  -8, -22,  -2,   9,   4],
                [  4,  -2,  -1,  27,  19, -25,  23,   3],
                [  3,   9, -28, -24, -22, -26,  10, -19],
                [-16, -29,  16,  22,   5,  -5, -20,  19]])

In [0]:
'''
output:
array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True],
       [ True,  True,  True, False, False, False, False,  True],
       [ True, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False]])
'''

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True],
       [ True,  True,  True, False, False, False, False,  True],
       [ True, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False]])

# 15
각 행의 평균 값을 구하기

In [0]:
arr = np.array([[ 16, -13,  18, -28,   6, -15,   7,  28],
                [ 19,  22,  25,  -8, -22,  -2,   9,   4],
                [  4,  -2,  -1,  27,  19, -25,  23,   3],
                [  3,   9, -28, -24, -22, -26,  10, -19],
                [-16, -29,  16,  22,   5,  -5, -20,  19]])


In [0]:
#output: array([  2.375,   5.875,   6.   , -12.125,  -1.   ])

array([  2.375,   5.875,   6.   , -12.125,  -1.   ])

# 16
각 열의 원소들이 전부 참이면 True, 하나라도 거짓이면 False를 갖는 불리언 배열을 반환

In [0]:
arr = np.array([[1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1],
                [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1],
                [1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1],
                [1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1]])

In [0]:
'''
output:
array([ True, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True,  True])
'''

array([ True, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True,  True])