In [0]:
import numpy as np

#1
주어진 리스트 x를 1차원의 numpy array로 바꿔보기. 데이터 타입은 np.float64 으로 지정해줄 것.

In [0]:
x = [10, 200, 100, -140, -60]

In [20]:
# output: array([  10.,  200.,  100., -140.,  -60.])

array([  10.,  200.,  100., -140.,  -60.])

# 2
가장자리만 0이고 안쪽은 전부 1인 (5,5) 매트릭스를 만들기.

In [21]:
'''
output:
array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])
'''
# 1. pad함수 없이.

# 2. np.pad함수 사용


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# 3
주어진 매트릭스(n, m)의 i번째 로우를 n-i번째 로우로 바꿔주는 코드를 작성

In [0]:
x = np.array([[ 0,  1,  2,  3,  4,  5,  6],
            [ 7,  8,  9, 10, 11, 12, 13],
            [14, 15, 16, 17, 18, 19, 20],
            [21, 22, 23, 24, 25, 26, 27],
            [28, 29, 30, 31, 32, 33, 34],
            [35, 36, 37, 38, 39, 40, 41]])

In [24]:
'''
output:
array([[35, 36, 37, 38, 39, 40, 41],
       [28, 29, 30, 31, 32, 33, 34],
       [21, 22, 23, 24, 25, 26, 27],
       [14, 15, 16, 17, 18, 19, 20],
       [ 7,  8,  9, 10, 11, 12, 13],
       [ 0,  1,  2,  3,  4,  5,  6]])
'''

array([[35, 36, 37, 38, 39, 40, 41],
       [28, 29, 30, 31, 32, 33, 34],
       [21, 22, 23, 24, 25, 26, 27],
       [14, 15, 16, 17, 18, 19, 20],
       [ 7,  8,  9, 10, 11, 12, 13],
       [ 0,  1,  2,  3,  4,  5,  6]])

# 4
주어진 배열에서 3의 배수이고, 50 보다 작거나 같은 원소만 추출.

In [0]:
x = np.array([46, 30, 11, 65, 64, 14, 61, 54, 62,  3,  8, 27, 33, 84,  9, 54, 56,
       54, 64, 26, 83, 16, 99, 24,  3, 29, 55, 90, 90, 42])

In [26]:
# output: array([30,  3, 27, 33,  9, 24,  3, 42])

array([30,  3, 27, 33,  9, 24,  3, 42])

# 5
주어진 배열의 차원, shape, 원소 개수를 구하기.

In [0]:
x = np.array([[[[5, 1, 2, 5, 7, 4, 2, 0, 4, 1, 7],
                [4, 3, 7, 6, 3, 1, 7, 8, 8, 0, 7]],
                [[9, 6, 0, 7, 4, 3, 4, 2, 2, 6, 8],
                [4, 2, 3, 5, 0, 5, 0, 9, 6, 5, 1]],
                [[2, 3, 4, 2, 4, 3, 9, 5, 8, 4, 6],
                [8, 0, 9, 8, 2, 7, 8, 2, 0, 0, 9]],
                [[4, 7, 0, 9, 8, 2, 5, 4, 1, 0, 5],
                [7, 0, 5, 3, 5, 9, 1, 2, 2, 5, 2]]],
            [[[0, 0, 0, 1, 3, 7, 1, 2, 5, 1, 4],
                [7, 3, 2, 8, 2, 2, 8, 6, 3, 8, 0]],
                [[6, 7, 9, 2, 1, 5, 1, 2, 7, 1, 6],
                [6, 1, 9, 7, 6, 3, 1, 3, 2, 8, 8]],
                [[1, 8, 2, 1, 1, 2, 8, 2, 1, 5, 3],
                [6, 7, 4, 2, 8, 4, 1, 2, 5, 2, 0]],
                [[6, 1, 6, 9, 7, 8, 8, 6, 6, 0, 1],
                [9, 2, 7, 3, 9, 6, 0, 4, 6, 3, 3]]]])

In [30]:
'''
output:
x의 dimension: 4
x의 shape: (2, 4, 2, 11)
x의 size: 176
'''

x의 dimension: 4
x의 shape: (2, 4, 2, 11)
x의 size: 176


# 6
주어진 배열 x와 같은 shape을 가지고, 원소는 모두 4인 배열 구하기

In [0]:
x = np.array([[[0.55769089, 0.23299233, 0.18249755, 0.9732918 , 0.02106981],
                        [0.23723868, 0.88100977, 0.11237681, 0.54849432, 0.14166628]],
                    [[0.40571156, 0.86052991, 0.08693893, 0.87787536, 0.22658562],
                        [0.28312625, 0.86719966, 0.04834027, 0.3603239 , 0.11649041]],
                    [[0.0101401 , 0.32296365, 0.41904702, 0.87439744, 0.90868535],
                        [0.04083139, 0.41187572, 0.55659584, 0.08919614, 0.59739324]]])

In [32]:
'''
output:
array([[[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]]])
'''

array([[[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]]])

# 7
-10에서 30 사이의 정수 중 랜덤하게 6개를 샘플링.

In [33]:
np.random.seed(123)
# output: array([-8, 18, 24, 28,  7,  9])

array([-8, 18, 24, 28,  7,  9])

# 8
주어진 배열을 랜덤하게 섞어보기

In [0]:
x = np.arange(30)

In [41]:
# 셔플 된 형태 (랜덤함)

[26  8 10 15  9 16 14 29 18  4 25  3  5  0 11 21 12 20 17  6  2 23 19 13
 28 22 27 24  1  7]


# 9
다음 배열의 (0, 4) 원소의 값은?

In [0]:
arr = np.array([[0.24729279, 0.15149773, 0.23264993, 0.57789104, 0.4754031 ,
                0.29082174, 0.65636695, 0.72398085, 0.12575465, 0.77784599],
            [0.66500578, 0.04162141, 0.94433265, 0.34871354, 0.8935809 ,
                0.75310631, 0.62090814, 0.45782245, 0.79072654, 0.26589272],
            [0.4236849 , 0.24108758, 0.15393337, 0.47541068, 0.38291606,
                0.85558059, 0.37261941, 0.69719457, 0.91373938, 0.36068192],
            [0.83447814, 0.2758488 , 0.97392625, 0.02931075, 0.09624108,
                0.82089376, 0.4507533 , 0.28030167, 0.55391228, 0.92006303],
            [0.86338432, 0.50512356, 0.90668294, 0.868307  , 0.13476902,
                0.16586259, 0.89588933, 0.45413397, 0.61715948, 0.17279922]])

In [42]:
# output: 0.4754031

0.4754031

# 10
다음 매트릭스(n, m)의 컬럼의 위치를 변경해보기  
0 -> 5  
1 -> 0  
2 -> 3  
3 -> 4  
4 -> 2  
5 -> 1  

In [0]:
arr = np.array([[0, 1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10, 11]])

In [44]:
'''
output:
array([[ 1,  5,  4,  2,  3,  0],
       [ 7, 11, 10,  8,  9,  6]])
'''

array([[ 1,  5,  4,  2,  3,  0],
       [ 7, 11, 10,  8,  9,  6]])

# 11
-1에서 1사이에서 균일한 간격의 점 15개로 구성된 배열을 만들기

In [45]:
'''
output:
array([-1.        , -0.85714286, -0.71428571, -0.57142857, -0.42857143,
       -0.28571429, -0.14285714,  0.        ,  0.14285714,  0.28571429,
        0.42857143,  0.57142857,  0.71428571,  0.85714286,  1.        ])
'''

array([-1.        , -0.85714286, -0.71428571, -0.57142857, -0.42857143,
       -0.28571429, -0.14285714,  0.        ,  0.14285714,  0.28571429,
        0.42857143,  0.57142857,  0.71428571,  0.85714286,  1.        ])

# 12
(4, 4) identity 매트릭스 만들기

In [46]:
'''
output:
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
'''

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 13
주어진 배열의 원소 사이사이에 100을 3번 넣어주어 새로운 배열 반환

In [0]:
arr = np.array([71, 73, 90, 91, 61, 43, 41, 86, 14])

In [48]:
'''
output:
array([ 71., 100., 100., 100.,  73., 100., 100., 100.,  90., 100., 100.,
       100.,  91., 100., 100., 100.,  61., 100., 100., 100.,  43., 100.,
       100., 100.,  41., 100., 100., 100.,  86., 100., 100., 100.,  14.])
'''

array([ 71., 100., 100., 100.,  73., 100., 100., 100.,  90., 100., 100.,
       100.,  91., 100., 100., 100.,  61., 100., 100., 100.,  43., 100.,
       100., 100.,  41., 100., 100., 100.,  86., 100., 100., 100.,  14.])

# 14
주어진 배열의 index가 0, 4, 5, 9, 12, 22 인 원소들의 값으로만 이루어진 새로운 배열 반환.

In [0]:
arr = np.array([4.837, 9.343, 5.621, 5.248, 4.597, 7.275, 1.878, 7.989, 8.169,
                5.78 , 5.35 , 9.075, 1.931, 1.825, 7.463, 3.791, 1.466, 4.441,
                9.785, 7.863, 9.53 , 2.804, 6.322, 4.314, 6.169])

In [50]:
# output: array([4.837, 4.597, 7.275, 5.78 , 1.931, 6.322])


array([4.837, 4.597, 7.275, 5.78 , 1.931, 6.322])